import { execFileSync } from 'node:child_process'
import { existsSync, mkdtempSync, writeFileSync, readFileSync, unlinkSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { url } from '@nuxt/test-utils/e2e'
import { test, expect } from 'vitest'
import type { E2EContext } from '../helpers'
import { getCliAuthToken } from '../helpers'

const cliEntry = fileURLToPath(new URL('../../../../../packages/cli/dist/index.mjs', import.meta.url))

function runCli(ctx: E2EContext, args: string[]) {
  const shelveUrl = new URL(url('/')).origin
  execFileSync(process.execPath, [cliEntry, ...args], {
    cwd: ctx.cliTmpDir,
    env: {
      ...process.env,
      SHELVE_URL: shelveUrl,
      SHELVE_TOKEN: ctx.cliToken,
      SHELVE_TEAM_SLUG: ctx.teamSlug,
      SHELVE_PROJECT: 'my app',
      SHELVE_DEFAULT_ENV: 'development',
      CI: '1',
    },
    stdio: 'pipe',
  })
}

export function registerCliTests(ctx: E2EContext) {
  test('CLI push uploads variables', async () => {
    ctx.cliToken = await getCliAuthToken(ctx.sessionCookie)
    ctx.cliTmpDir = mkdtempSync(join(tmpdir(), 'shelve-cli-e2e-'))

    writeFileSync(
      join(ctx.cliTmpDir, 'package.json'),
      JSON.stringify({ name: 'cli-e2e' }),
    )

    writeFileSync(
      join(ctx.cliTmpDir, 'shelve.json'),
      JSON.stringify({
        project: 'my app',
        slug: 'e2e-team',
      }),
    )

    writeFileSync(join(ctx.cliTmpDir, '.env'), 'CLI_E2E=hello-from-push\n')

    runCli(ctx, ['push'])

    const variables = await ctx.api(`/api/teams/${ctx.teamSlug}/projects/${ctx.projectId}/variables`)

    const row = variables.find((v: { key: string }) => v.key === 'CLI_E2E')
    expect(row).toBeDefined()
    expect(
      row!.values.some((x: { value: string }) => x.value === 'hello-from-push'),
    ).toBe(true)
  })

  test('CLI pull writes .env from remote', () => {
    unlinkSync(join(ctx.cliTmpDir!, '.env'))

    runCli(ctx, ['pull'])

    const content = readFileSync(join(ctx.cliTmpDir!, '.env'), 'utf-8')

    expect(content).toContain('# Generated by Shelve CLI')
    expect(content).toContain('CLI_E2E=hello-from-push')
  })

  test('CLI pull also generates .env.example', () => {
    const examplePath = join(ctx.cliTmpDir!, '.env.example')
    expect(existsSync(examplePath)).toBe(true)

    const content = readFileSync(examplePath, 'utf-8')
    expect(content).toContain('# Generated by Shelve CLI')
    expect(content).toContain('CLI_E2E=')
    expect(content).not.toContain('CLI_E2E=hello-from-push')
  })
}
