import { parseEnvFile } from '@utils'
import type {
  EnvVar,
  EnvVarExport,
  CreateEnvFileInput,
  PushEnvFileInput,
  PushEnvFileResult,
  CreateVariablesInput,
  GetEnvVariables
} from '@types'
import { cliWarn } from '../utils/output'
import { loadShelveConfig, askBoolean } from '../utils'
import { FileService } from './file'
import { BaseService } from './base'

export class EnvService extends BaseService {

  static formatEnvContent(variables: EnvVarExport[]): string {
    const grouped = new Map<string, { description: string; vars: EnvVarExport[] }>()
    const ungrouped: EnvVarExport[] = []

    for (const variable of variables) {
      if (variable.group) {
        const existing = grouped.get(variable.group.name)
        if (existing) {
          existing.vars.push(variable)
        } else {
          grouped.set(variable.group.name, {
            description: variable.group.description,
            vars: [variable],
          })
        }
      } else {
        ungrouped.push(variable)
      }
    }

    const lines: string[] = ['# Generated by Shelve CLI']

    for (const [name, { description, vars }] of grouped) {
      lines.push('')
      lines.push(`# ---- ${name} ----`)
      if (description) lines.push(`# ${description}`)
      for (const v of vars) {
        if (v.description) lines.push(`# ${v.description}`)
        lines.push(`${v.key}=${v.value}`)
      }
    }

    if (ungrouped.length > 0) {
      if (grouped.size > 0) lines.push('')
      for (const v of ungrouped) {
        if (v.description) lines.push(`# ${v.description}`)
        lines.push(`${v.key}=${v.value}`)
      }
    }

    return lines.join('\n')
  }

  static async getEnvFile(): Promise<EnvVar[]> {
    const { envFileName } = await loadShelveConfig()

    if (FileService.exists(envFileName)) {
      const envFile = FileService.read(envFileName)
      return parseEnvFile(envFile)
    }
    FileService.write(envFileName, '')
    return []
  }

  static async createEnvFile(input: CreateEnvFileInput): Promise<void> {
    const { envFileName, variables, confirmChanges, pullMode = 'replace' } = input

    if (confirmChanges)
      await askBoolean(`Are you sure you want to update ${envFileName} file?`)

    await this.withLoading(`Creating ${envFileName} and ${envFileName}.example files`, async () => {
      const content = this.formatEnvContent(variables)

      if (pullMode === 'replace' && FileService.exists(envFileName)) FileService.delete(envFileName)
      FileService.write(envFileName, content)

      const exampleVars: EnvVarExport[] = variables.map((v) => ({
        key: v.key,
        value: '',
        description: v.description,
        group: v.group,
      }))
      FileService.write(`${envFileName}.example`, this.formatEnvContent(exampleVars))

      // TODO: make withLoading work without setTimeout
      await new Promise((resolve) => setTimeout(resolve, 10))
    })
  }

  static getEnvVariables(input: GetEnvVariables & { quiet?: boolean }): Promise<EnvVarExport[]> {
    const { project, environmentId, slug, quiet } = input
    const endpoint = `/teams/${slug}/projects/${project.id}/variables/env/${environmentId}`
    if (quiet) return this.request<EnvVarExport[]>(endpoint)
    return this.withLoading('Fetch variables', () => this.request<EnvVarExport[]>(endpoint))
  }

  static async pushEnvFile(input: PushEnvFileInput): Promise<PushEnvFileResult> {
    const { variables, project, slug, environment, confirmChanges, autoUppercase } = input

    if (variables.length === 0) {
      cliWarn('No variables to push')
      return { pushed: false, variableCount: 0, skippedKeys: [], conflictKeys: [] }
    }

    if (confirmChanges)
      await askBoolean(`Are you sure you want to push ${variables.length} variables to ${environment.name} environment?`)

    await this.withLoading('Pushing variables', async () => {
      const body: CreateVariablesInput = {
        projectId: project.id,
        autoUppercase,
        environmentIds: [environment.id],
        variables: variables.map((variable) => ({
          key: variable.key,
          value: variable.value
        }))
      }
      await this.request<EnvVar[]>(`/teams/${slug}/projects/${project.id}/variables`, {
        method: 'POST',
        body
      })
    })

    return { pushed: true, variableCount: variables.length, skippedKeys: [], conflictKeys: [] }
  }

  static async generateEnvExampleFile(): Promise<void> {
    const { envFileName } = await loadShelveConfig()
    const envExampleFile = `${envFileName}.example`

    await this.withLoading(`Generating ${envExampleFile} file`, async () => {
      const variables = await this.getEnvFile()

      const exampleVars: EnvVarExport[] = variables.map((v) => ({
        key: v.key,
        value: 'your_value',
      }))

      FileService.write(envExampleFile, this.formatEnvContent(exampleVars))
    })
  }

}
