CREATE TABLE "vercel_integration" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "vercel_integration_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"configurationId" varchar(50) NOT NULL,
	"accessToken" varchar(800) NOT NULL,
	"teamId" varchar(50),
	"userId" bigint NOT NULL,
	"updatedAt" timestamp NOT NULL,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "vercel_integration_configurationId_unique" UNIQUE("configurationId")
);
--> statement-breakpoint
ALTER TABLE "projects" ADD COLUMN "vercelProjectId" varchar(50) DEFAULT '';--> statement-breakpoint
ALTER TABLE "vercel_integration" ADD CONSTRAINT "vercel_integration_userId_users_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;