name: "🚀 Feature request"
description: Suggest an idea or enhancement for the project.
labels: ["feature"]
title: "feat: "
body:
  - type: markdown
    attributes:
      value: |
        Before requesting a feature, please make sure that you have read through our [documentation](https://shelve.cloud/getting-started) and existing [issues](https://github.com/HugoRCD/shelve/issues) to see if the feature has already been requested or implemented. If it has, please add your reaction to the existing issue instead of creating a new one.
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what you think would be an helpful addition to the project, including the possible use cases and alternatives you have considered.
    validations:
      required: true
  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: If applicable, add any other context or screenshots here.
