# documentation: https://shelve.cloud/docs/getting-started
# slogan: Shelve - Secure environment sharing for collaborative development
# tags: environment variables, projects management, collaboration, cli, secure sharing
# port: 3000

services:
  app:
    image: 'ghcr.io/hugorcd/shelve:latest'
    restart: always
    environment:
      - SERVICE_FQDN_APP=/
      - 'DATABASE_URL=postgres://shelve:${SERVICE_PASSWORD_POSTGRES}@postgres:5432/shelve'
      - 'NUXT_PRIVATE_REDIS_URL=${NUXT_PRIVATE_REDIS_URL:-redis://redis:6379}'
      - 'NUXT_PRIVATE_ENCRYPTION_KEY=${SERVICE_PASSWORD_SHELVE}'
      - 'NUXT_SESSION_PASSWORD=${SERVICE_PASSWORD_SHELVE}'
      - 'NUXT_OAUTH_GITHUB_CLIENT_ID=${NUXT_OAUTH_GITHUB_CLIENT_ID}'
      - 'NUXT_OAUTH_GITHUB_CLIENT_SECRET=${NUXT_OAUTH_GITHUB_CLIENT_SECRET}'
      - 'NUXT_OAUTH_GOOGLE_CLIENT_ID=${NUXT_OAUTH_GOOGLE_CLIENT_ID}'
      - 'NUXT_OAUTH_GOOGLE_CLIENT_SECRET=${NUXT_OAUTH_GOOGLE_CLIENT_SECRET}'
      - 'NUXT_PRIVATE_RESEND_API_KEY=${NUXT_PRIVATE_RESEND_API_KEY}'
      - 'NUXT_PRIVATE_SENDER_EMAIL=${NUXT_PRIVATE_SENDER_EMAIL}'
      - 'NUXT_PRIVATE_ADMIN_EMAILS=${NUXT_PRIVATE_ADMIN_EMAILS}'
      - 'NUXT_PRIVATE_ALLOWED_ORIGINS=${SERVICE_FQDN_APP}'
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
    healthcheck:
      test:
        - CMD
        - curl
        - '-f'
        - 'http://localhost:3000/api/hello'
      interval: 30s
      timeout: 10s
      retries: 3
    logging:
      driver: json-file
      options:
        max-size: '10m'
        max-file: '3'
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M
  postgres:
    image: 'postgres:17-alpine'
    restart: always
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    environment:
      POSTGRES_USER: shelve
      POSTGRES_PASSWORD: '${SERVICE_PASSWORD_POSTGRES}'
      POSTGRES_DB: shelve
    healthcheck:
      test:
        - CMD
        - pg_isready
        - '-U'
        - shelve
      interval: 30s
      timeout: 10s
      retries: 3
  redis:
    image: 'redis:7.4-alpine'
    restart: always
    volumes:
      - 'redis:/data'
    healthcheck:
      test:
        - CMD
        - redis-cli
        - ping
      interval: 30s
      timeout: 10s
      retries: 3
volumes:
  postgres: null
  redis: null
