import { describe, test, expect } from 'vitest'
import { EnvService } from '../src/services/env'

describe('EnvService.formatEnvContent', () => {
  test('formats ungrouped variables', () => {
    const result = EnvService.formatEnvContent([
      { key: 'FOO', value: 'bar' },
      { key: 'BAZ', value: 'qux' },
    ])

    expect(result).toBe([
      '# Generated by Shelve CLI',
      'FOO=bar',
      'BAZ=qux',
    ].join('\n'))
  })

  test('formats variables with descriptions', () => {
    const result = EnvService.formatEnvContent([
      { key: 'API_KEY', value: 'secret', description: 'Main API key' },
      { key: 'DB_URL', value: 'postgres://localhost' },
    ])

    expect(result).toBe([
      '# Generated by Shelve CLI',
      '# Main API key',
      'API_KEY=secret',
      'DB_URL=postgres://localhost',
    ].join('\n'))
  })

  test('formats grouped variables with group headers', () => {
    const result = EnvService.formatEnvContent([
      { key: 'DB_HOST', value: 'localhost', group: { name: 'Database', description: 'DB settings' } },
      { key: 'DB_PORT', value: '5432', group: { name: 'Database', description: 'DB settings' } },
    ])

    expect(result).toBe([
      '# Generated by Shelve CLI',
      '',
      '# ---- Database ----',
      '# DB settings',
      'DB_HOST=localhost',
      'DB_PORT=5432',
    ].join('\n'))
  })

  test('formats grouped variables with variable descriptions', () => {
    const result = EnvService.formatEnvContent([
      {
        key: 'DB_HOST',
        value: 'localhost',
        description: 'Database hostname',
        group: { name: 'Database', description: 'Connection config' },
      },
      {
        key: 'DB_PORT',
        value: '5432',
        description: 'Database port',
        group: { name: 'Database', description: 'Connection config' },
      },
    ])

    expect(result).toBe([
      '# Generated by Shelve CLI',
      '',
      '# ---- Database ----',
      '# Connection config',
      '# Database hostname',
      'DB_HOST=localhost',
      '# Database port',
      'DB_PORT=5432',
    ].join('\n'))
  })

  test('separates multiple groups with blank lines', () => {
    const result = EnvService.formatEnvContent([
      { key: 'GH_TOKEN', value: 'ghp_xxx', group: { name: 'GitHub', description: '' } },
      { key: 'DB_URL', value: 'pg://...', group: { name: 'Database', description: 'DB config' } },
    ])

    expect(result).toBe([
      '# Generated by Shelve CLI',
      '',
      '# ---- GitHub ----',
      'GH_TOKEN=ghp_xxx',
      '',
      '# ---- Database ----',
      '# DB config',
      'DB_URL=pg://...',
    ].join('\n'))
  })

  test('places ungrouped variables after grouped ones', () => {
    const result = EnvService.formatEnvContent([
      { key: 'DB_HOST', value: 'localhost', group: { name: 'Database', description: '' } },
      { key: 'NODE_ENV', value: 'production' },
    ])

    expect(result).toBe([
      '# Generated by Shelve CLI',
      '',
      '# ---- Database ----',
      'DB_HOST=localhost',
      '',
      'NODE_ENV=production',
    ].join('\n'))
  })

  test('omits group description comment when empty', () => {
    const result = EnvService.formatEnvContent([{ key: 'KEY', value: 'val', group: { name: 'NoDesc', description: '' } }])

    expect(result).not.toContain('# \n')
    expect(result).toContain('# ---- NoDesc ----')
    expect(result).toContain('KEY=val')
    const lines = result.split('\n')
    const headerIdx = lines.indexOf('# ---- NoDesc ----')
    expect(lines[headerIdx + 1]).toBe('KEY=val')
  })

  test('generates .env.example format with empty values', () => {
    const vars = [
      { key: 'DB_HOST', value: 'localhost', description: 'Database host', group: { name: 'Database', description: 'DB config' } },
      { key: 'API_KEY', value: 'secret' },
    ]
    const exampleVars = vars.map(v => ({
      key: v.key,
      value: '',
      description: v.description,
      group: v.group,
    }))

    const result = EnvService.formatEnvContent(exampleVars)

    expect(result).toContain('DB_HOST=')
    expect(result).not.toContain('DB_HOST=localhost')
    expect(result).toContain('API_KEY=')
    expect(result).not.toContain('API_KEY=secret')
    expect(result).toContain('# Database host')
    expect(result).toContain('# ---- Database ----')
  })
})
