CREATE TABLE "variable_groups" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "variable_groups_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"name" varchar(50) NOT NULL,
	"description" varchar(500) DEFAULT '' NOT NULL,
	"position" integer DEFAULT 0 NOT NULL,
	"projectId" bigint NOT NULL,
	"updatedAt" timestamp NOT NULL,
	"createdAt" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "variables" ADD COLUMN "description" varchar(500);--> statement-breakpoint
ALTER TABLE "variables" ADD COLUMN "groupId" bigint;--> statement-breakpoint
ALTER TABLE "variable_groups" ADD CONSTRAINT "variable_groups_projectId_projects_id_fk" FOREIGN KEY ("projectId") REFERENCES "public"."projects"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "variable_groups_project_name_idx" ON "variable_groups" USING btree ("projectId","name");--> statement-breakpoint
CREATE INDEX "variable_groups_project_idx" ON "variable_groups" USING btree ("projectId");--> statement-breakpoint
ALTER TABLE "variables" ADD CONSTRAINT "variables_groupId_variable_groups_id_fk" FOREIGN KEY ("groupId") REFERENCES "public"."variable_groups"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "variables_group_idx" ON "variables" USING btree ("groupId");