CREATE TABLE "audit_logs" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "audit_logs_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"teamId" bigint,
	"actorType" varchar(16) NOT NULL,
	"actorId" bigint,
	"action" varchar(64) NOT NULL,
	"resourceType" varchar(32),
	"resourceId" varchar(64),
	"ip" varchar(45),
	"userAgent" varchar(256),
	"metadata" jsonb,
	"createdAt" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "audit_logs" ADD CONSTRAINT "audit_logs_teamId_teams_id_fk" FOREIGN KEY ("teamId") REFERENCES "public"."teams"("id") ON DELETE cascade ON UPDATE no action;
--> statement-breakpoint
CREATE INDEX "audit_logs_team_idx" ON "audit_logs" USING btree ("teamId");
--> statement-breakpoint
CREATE INDEX "audit_logs_created_idx" ON "audit_logs" USING btree ("createdAt");
--> statement-breakpoint
CREATE INDEX "audit_logs_team_created_idx" ON "audit_logs" USING btree ("teamId","createdAt");
--> statement-breakpoint
CREATE INDEX "audit_logs_action_idx" ON "audit_logs" USING btree ("action");
