CREATE TYPE "public"."cli_device_auth_status" AS ENUM('pending', 'approved', 'denied', 'expired');--> statement-breakpoint
CREATE TABLE "cli_device_auth" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "cli_device_auth_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"deviceCodeHash" varchar(64) NOT NULL,
	"userCode" varchar(9) NOT NULL,
	"status" "cli_device_auth_status" DEFAULT 'pending' NOT NULL,
	"userId" bigint,
	"tokenId" bigint,
	"accessToken" varchar(128),
	"clientMeta" jsonb,
	"expiresAt" timestamp NOT NULL,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "cli_device_auth_deviceCodeHash_unique" UNIQUE("deviceCodeHash"),
	CONSTRAINT "cli_device_auth_userCode_unique" UNIQUE("userCode")
);--> statement-breakpoint
ALTER TABLE "cli_device_auth" ADD CONSTRAINT "cli_device_auth_userId_users_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "cli_device_auth" ADD CONSTRAINT "cli_device_auth_tokenId_tokens_id_fk" FOREIGN KEY ("tokenId") REFERENCES "public"."tokens"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "cli_device_auth_user_code_idx" ON "cli_device_auth" USING btree ("userCode");--> statement-breakpoint
CREATE INDEX "cli_device_auth_expires_idx" ON "cli_device_auth" USING btree ("expiresAt");
