import fs from 'fs'
import type {
  CreateEnvFileInput,
  CreateVariablesInput,
  EnvVar,
  PushEnvFileInput
} from '@shelve/types'
import { confirm, spinner } from '@clack/prompts'
import { parseEnvFile } from '@shelve/utils'
import { loadShelveConfig } from './config'
import { getToken, useApi } from './api'
import { onCancel } from './index'

const s = spinner()

export function isEnvFileExist(envFileName: string): boolean {
  return fs.existsSync(envFileName)
}

export async function getKeyValue(key: string): Promise<string> {
  const { envFileName } = await loadShelveConfig(false)
  const envFile = await getEnvFile()
  const value = envFile.find((item) => item.key === key)?.value
  if (!value) {
    if (key === 'SHELVE_TOKEN') return await getToken()
    onCancel(`Key ${key} not found in ${envFileName}`)
  }
  return value
}

export async function mergeEnvFile(variables: EnvVar[] = []): Promise<void> {
  const { envFileName } = await loadShelveConfig(false)
  s.start(`Merging ${envFileName} file`)
  const envFile = await getEnvFile()
  envFile.push(...variables)
  const content = envFile.map((item) => `${ item.key }=${ item.value }`).join('\n')
  const finalString = `# Generated by Shelve CLI\n${content}`
  fs.writeFileSync(envFileName, finalString, { encoding: 'utf8' })
  s.stop(`Merging ${envFileName} file`)
}

export async function createEnvFile(input: CreateEnvFileInput): Promise<void> {
  const { envFileName, variables, confirmChanges } = input
  if (confirmChanges) {
    const update = await confirm({
      message: `Are you sure you want to update ${envFileName} file?`,
    })
    if (!update) return onCancel('Operation cancelled.')
  }
  const envFileExist = isEnvFileExist(envFileName)
  try {
    s.start(`Creating ${envFileName} file`)
    const content = variables.map((item) => `${ item.key }=${ item.value }`).join('\n')
    const finalString = `# Generated by Shelve CLI\n${content}`
    if (envFileExist) fs.unlinkSync(envFileName)
    fs.writeFileSync(envFileName, finalString)
    s.stop(`Creating ${envFileName} file`)
  } catch (e) {
    onCancel(`Failed to create ${ envFileName } file`)
  }
}

export async function getEnvFile(): Promise<EnvVar[]> {
  const { envFileName } = await loadShelveConfig(false)
  const isExist = fs.existsSync(envFileName)
  if (isExist) {
    const envFile = fs.readFileSync(envFileName, 'utf8')
    return parseEnvFile(envFile)
  }
  return []
}

export async function getEnvVariables(projectId: number, environmentId: number): Promise<EnvVar[]> {
  const api = await useApi()

  s.start('Fetching variables')
  try {
    const variables = await api(`/variables/project/${projectId}/${environmentId}`)
    s.stop('Fetching variables')
    return variables
  } catch (e) {
    onCancel('Failed to fetch variables')
  }
}

export async function pushEnvFile(input: PushEnvFileInput): Promise<void> {
  const { variables, projectId, environment, confirmChanges, autoUppercase } = input
  if (confirmChanges) {
    const update = await confirm({
      message: `Are you sure you want to push ${variables.length} variables to ${environment.name} environment?`,
    })
    if (!update) return onCancel('Operation cancelled.')
  }
  const api = await useApi()

  s.start('Pushing variables')
  try {
    const body: CreateVariablesInput = {
      projectId,
      autoUppercase,
      environmentIds: [environment.id],
      variables: variables.map((variable) => ({
        key: variable.key,
        value: variable.value
      }))
    }
    await api(`/variables`, { method: 'POST', body })
    s.stop('Pushing variables')
  } catch (e) {
    onCancel('Failed to push variables')
  }
}

export async function generateEnvExampleFile(): Promise<void> {
  const { envFileName } = await loadShelveConfig(false)
  const envExampleFile = `${envFileName}.example`

  s.start(`Generating ${envExampleFile} file`)

  try {
    const variables = await getEnvFile()
    const keys = variables.map((variable) => variable.key)

    fs.writeFileSync(envExampleFile, `# Generated by Shelve CLI\n${keys.map((key) => `${key}=your_value`).join('\n')}`)
    s.stop(`Generating ${envExampleFile} file`)
  } catch (e) {
    onCancel(`Failed to generate ${envExampleFile} file`)
  }
}
